### ISSUE TITLE
[Listbox] Add keyboard navigation to Listbox

### ISSUE THREAD

**Issue by ashleemboyer** [ashleemboyer/a11y-components-og#5]
# What's the problem?

The new Listbox component needs to work with a keyboard. I'll comb [the WAI-ARIA docs](https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190814/#listbox_kbd_interaction) and note all the requirements in the next section.

## TODO

_Note: these requirements are for the single-select, vertically arranged listbox. Multi-select and horizontally arranged options may come later._

**When the Listbox receives focus**
- [ ] If none of the options are selected before receiving focus, the first option receives focus and is automatically selected and receives focus
- [ ] If an option is selected before the Listbox receives focus, focus is set on the selected option.

**Down, Up, Home, & End**
With each of these keys, selection follows focus.
- [ ] Down arrow: Moves focus to the next option.
- [ ] Up Arrow: Moves focus to the previous option.
- [ ] Home: Moves focus to the first option.
- [ ] End: Moves focus to the last option.

**Type ahead**
- [ ] Type one character: moves focus to the next item with a name that starts with the typed character.
- [ ] Type multiple characters in rapid succession: moves focus to the next item with a name that starts with the string of characters typed.

**Comment by ashleemboyer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Listbox] Keyboard navigation](https://trello.com/c/S1TaSUnC/4-listbox-keyboard-navigation)
